Add logging
- Because getting this error when sending /blast from Slack channel
2021-04-15T16:04:38.829867241Z [2021-04-15 16:04:38 +0000] [38] [ERROR] Error handling request /slack/events
2021-04-15T16:04:38.829948342Z Traceback (most recent call last):
2021-04-15T16:04:38.829956042Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
2021-04-15T16:04:38.829960642Z     self.handle_request(listener, req, client, addr)
2021-04-15T16:04:38.829964842Z   File "/opt/python/3.8.6/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
2021-04-15T16:04:38.829969042Z     respiter = self.wsgi(environ, resp.start_response)
2021-04-15T16:04:38.829973042Z TypeError: __call__() missing 1 required positional argument: 'send'
2021-04-15T16:04:38.839147510Z 172.16.0.1 - - [15/Apr/2021:16:04:38 +0000] "POST /slack/events HTTP/1.1" 500 0 "-" "-"